### ISSUE TITLE
在微信开发工具里运行说没找到app.json

### ISSUE THREAD

**Issue by imggni** [673800357/mpvue-cnode#1]
在微信开发工具里运行说没找到app.json ，这个是什么原因啊，刚学这个，所以来膜拜下大神的代码，学习一下，您写的代码

**Comment by flytam** [comment]
@imggni  开发者工具打开dist目录，你应该是开发者工具打开的是根目录吧

**Comment by 673800357** [comment]
@imggni  我也不是大神，todo里面也有一些目前还没完成的功能和一些待优化的地方欢迎提pr一起共同学习

**Comment by imggni** [comment]
我之前都没做过小程序，才刚学，多谢您的帮助

**Comment by linguitang** [comment]
dist目录在哪

**Comment by flytam** [comment]
@linguitang 
直接项目根目录下npm install然后npm run dev使用微信开发者工具打开目录就可以预览了。
