### ISSUE TITLE
不是bug

### ISSUE THREAD

**Issue by p0301y** [673800357/mpvue-cnode#5]
你好！我在将项目clone到本地，然后用小程序测试工具打开，而且project.config.json中配置了appid等信息，出现错误：登录用户不是该小程序的开发者 ，其他clone的项目是正常的，该如何解决

**Comment by flytam** [comment]
能提供下截图信息吗？开发者工具报的错？

**Comment by p0301y** [comment]
我的问题，我申请一个appid就可以了，谢谢！~
