### ISSUE TITLE
提几个个人建议

### ISSUE THREAD

**Issue by awong1900** [673800357/mpvue-cnode#6]
首先感谢楼主开源出来。整个框架和功能形态都很完善了。特别是扫描登录都做了。
我是下载编译，用了我自己部署的教练社区 https://bbs.zuqiuxunlian.com 的API做的测试哦。

有几个问题：
1. 单屏显示的条数只有3个主题（iphone7），这太少了，太不紧凑。对于社区来讲，浏览非常没有效率。
2. 下拉一点点，就会提示加载，是不是多加载列表内容？
3. 内容包含链接，不会提示点击。 我猜可能是小程序规则导致的吧。
4. 增加转发选项。分享到微信群就比较方便了。

排版我认为 虎扑足球小程序还不错。  加油。 我是你的小测试。

**Comment by flytam** [comment]
感谢建议哈，你提的几点我都非常赞同。因为当时只是当个练手项目，很多体验和设计上的问题都没有考虑好，我看了下你的项目。也非常不错，感谢鼓励哈哈

**Comment by awong1900** [comment]
现在想了想，用小程序做社区不够理想，限制比较多。 好像微信也不开放社区类型应用上架。

**Comment by awong1900** [comment]
LZ 有没有兴趣帮忙做一个客户端，把界面好好改一下就可以。
